<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <AssemblyName>ManagerGui</AssemblyName>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
  </PropertyGroup>

</Project>
